import type { LucideIcon } from "lucide-react"
import { Wifi, Monitor, Zap, Shield, Volume2, HardDrive, Printer, Usb } from "lucide-react"

export interface CommunityFix {
  slug: string
  title: string
  description: string
  longDescription: string
  category: string
  icon: LucideIcon
  fixPrompt: string
  downloads: number
}

export const COMMUNITY_FIXES: CommunityFix[] = [
  {
    slug: "wifi-disconnecting",
    title: "WiFi Keeps Disconnecting",
    description: "Resets network adapter, DNS cache, and TCP stack to fix random WiFi disconnections.",
    longDescription: "If your WiFi keeps dropping or disconnecting every few minutes, this fix resets your network adapter, flushes the DNS cache, resets the TCP/IP stack, and re-enables the WiFi adapter. It also resets Winsock and clears the ARP cache. This resolves the most common causes of WiFi disconnection on Windows 10 and 11.",
    category: "Fix Tools",
    icon: Wifi,
    fixPrompt: "My WiFi keeps disconnecting randomly every few minutes. I have to reconnect manually each time.",
    downloads: 4820,
  },
  {
    slug: "windows-update-stuck",
    title: "Windows Update Stuck",
    description: "Repairs broken Windows Update service, clears update cache, and re-registers components.",
    longDescription: "When Windows Update gets stuck downloading, fails to install updates, or shows error codes, this fix stops the update services, clears the SoftwareDistribution and catroot2 cache folders, re-registers the update DLLs, and restarts the services. It resolves the most common update issues without reinstalling Windows.",
    category: "Fix Tools",
    icon: Monitor,
    fixPrompt: "Windows Update is stuck and won't download or install updates. It keeps saying 0% or gives an error.",
    downloads: 6340,
  },
  {
    slug: "slow-pc",
    title: "Slow PC Performance",
    description: "Cleans startup programs, clears caches, frees disk space, and optimizes power settings.",
    longDescription: "If your PC feels slow and sluggish, this fix disables unnecessary startup programs, clears temp files and system caches, optimizes the power plan for performance, disables visual effects, and cleans up the Recycle Bin. It targets the most common causes of slow Windows performance.",
    category: "Fix Tools",
    icon: Zap,
    fixPrompt: "My PC is really slow. Everything takes forever to load and programs freeze often.",
    downloads: 8910,
  },
  {
    slug: "audio-not-working",
    title: "Audio Not Working",
    description: "Resets audio services, reinstalls audio drivers, and fixes common sound issues.",
    longDescription: "When your speakers or headphones stop producing sound, this fix restarts the Windows Audio service, re-registers the audio DLL, reinstalls the default audio driver, and resets audio enhancements. It resolves the most common audio problems including no sound, crackling, and missing playback devices.",
    category: "Fix Tools",
    icon: Volume2,
    fixPrompt: "My audio stopped working completely. There is no sound from speakers or headphones.",
    downloads: 3150,
  },
  {
    slug: "disk-errors",
    title: "Disk Error Repair",
    description: "Runs CHKDSK on your drive to repair file system errors and bad sectors.",
    longDescription: "This fix runs Windows CHKDSK on your primary drive to scan for and repair file system errors, cross-linked files, and bad sectors. It schedules the scan for the next reboot since the drive is in use, and shows you the results after restart.",
    category: "Fix Tools",
    icon: HardDrive,
    fixPrompt: "I'm getting disk read errors and my drive seems to have problems. Windows is running CHKDSK sometimes on boot.",
    downloads: 2280,
  },
  {
    slug: "printer-not-working",
    title: "Printer Not Working",
    description: "Resets print spooler, clears print queue, and reinstalls printer drivers.",
    longDescription: "When your printer won't print, shows offline, or has stuck jobs in the queue, this fix stops the print spooler, clears the print queue, re-registers printer DLLs, and restarts the spooler service. It also removes and reinstalls the default printer driver.",
    category: "Fix Tools",
    icon: Printer,
    fixPrompt: "My printer is not working. Print jobs are stuck in the queue and the printer shows as offline.",
    downloads: 1970,
  },
  {
    slug: "usb-device-not-recognized",
    title: "USB Device Not Recognized",
    description: "Resets USB controllers, clears device cache, and fixes unrecognized USB devices.",
    longDescription: "When Windows shows 'USB device not recognized' or a USB device stops working, this fix resets all USB controllers, clears the USB device cache, and reinstalls USB drivers. It resolves the most common USB problems without affecting your files or settings.",
    category: "Fix Tools",
    icon: Usb,
    fixPrompt: "My USB device is not recognized. Windows keeps showing an error that the USB device has malfunctioned.",
    downloads: 2640,
  },
  {
    slug: "privacy-protector",
    title: "Disable Windows Telemetry",
    description: "Disables telemetry services, blocks tracking domains, and turns off advertising ID.",
    longDescription: "Windows collects significant data by default. This fix disables the DiagTrack and dmwappushservice telemetry services, blocks Microsoft tracking domains in the hosts file, disables the advertising ID, and turns off activity history. It preserves all functionality while protecting your privacy.",
    category: "Privacy & Security",
    icon: Shield,
    fixPrompt: "I want to stop Windows from spying on me. Disable all telemetry, tracking, and data collection.",
    downloads: 7420,
  },
  {
    slug: "bluescreen-recovery",
    title: "Blue Screen Recovery",
    description: "Reads Windows error logs, identifies BSOD causes, and applies targeted fixes.",
    longDescription: "If you're getting blue screen errors (BSOD), this fix reads the Windows event logs to identify the root cause, checks for problematic drivers, verifies system file integrity with SFC, and applies targeted repairs. It includes a safety scan before making any changes.",
    category: "Fix Tools",
    icon: Monitor,
    fixPrompt: "I keep getting blue screen errors. The computer crashes randomly with a blue screen.",
    downloads: 5690,
  },
  {
    slug: "corrupted-files",
    title: "Repair Corrupted System Files",
    description: "Runs System File Checker and DISM to repair corrupted Windows files.",
    longDescription: "When Windows system files are corrupted, you might see random errors, crashes, or missing features. This fix runs SFC (System File Checker) and DISM to scan and repair all corrupted system files. It also creates a restore point before starting.",
    category: "Fix Tools",
    icon: HardDrive,
    fixPrompt: "I think my Windows system files are corrupted. I'm getting errors and some things don't work right.",
    downloads: 4470,
  },
  {
    slug: "display-resolution",
    title: "Fix Display Resolution",
    description: "Resets display settings, reinstalls GPU driver, and restores correct resolution.",
    longDescription: "When your display is stuck at the wrong resolution, everything looks blurry, or you can't find the right resolution in settings, this fix reinstalls your display adapter driver, resets the display configuration, and restores the recommended resolution for your monitor.",
    category: "Fix Tools",
    icon: Monitor,
    fixPrompt: "My display resolution is wrong and I can't set it to the correct resolution. Everything looks stretched or blurry.",
    downloads: 1830,
  },
  {
    slug: "network-speed",
    title: "Speed Up Network and Internet",
    description: "Switches to fastest DNS, optimizes TCP, and removes bandwidth throttling.",
    longDescription: "Windows limits your network speed by default. This fix sets DNS to Cloudflare and Google for faster browsing, optimizes TCP settings for maximum throughput, removes the 20% bandwidth reservation, and disables Nagle's algorithm for lower latency.",
    category: "Performance",
    icon: Wifi,
    fixPrompt: "My internet speed is slow. I want to optimize my network settings for faster browsing and lower latency.",
    downloads: 5210,
  },
  {
    slug: "dark-mode",
    title: "Enable Dark Mode System-Wide",
    description: "Enables dark mode for all Windows elements and supported applications.",
    longDescription: "This fix enables system-wide dark mode including the taskbar, Start Menu, Settings, File Explorer, and all supported apps. It also sets the default app mode to dark and disables the light theme entirely for a consistent dark experience.",
    category: "Customization",
    icon: Monitor,
    fixPrompt: "I want to enable dark mode everywhere on my Windows PC. Set dark mode for all system elements and apps.",
    downloads: 6890,
  },
  {
    slug: "god-mode",
    title: "Enable God Mode",
    description: "Creates the hidden God Mode folder with access to every system setting in one place.",
    longDescription: "God Mode is a hidden Windows folder that gives you access to over 200 system settings and control panel options in one convenient list. This fix creates the God Mode folder on your Desktop so you can quickly find any Windows setting without navigating through menus.",
    category: "Customization",
    icon: Monitor,
    fixPrompt: "I want to enable God Mode on Windows. Create the God Mode folder with all system settings.",
    downloads: 3560,
  },
  {
    slug: "startup-optimization",
    title: "Disable Unnecessary Startup Programs",
    description: "Scans and disables common unnecessary startup programs for faster boot time.",
    longDescription: "Too many programs launching at startup makes your PC boot slowly and wastes resources. This fix disables common unnecessary startup items like OneDrive, Microsoft Teams, Skype, Discord, Spotify, Steam, and Edge background processes. You can still open these apps manually when you need them.",
    category: "Performance",
    icon: Zap,
    fixPrompt: "My PC takes a long time to boot. Too many programs are starting up with Windows. Disable unnecessary startup programs.",
    downloads: 7140,
  },
  {
    slug: "full-performance-boost",
    title: "Full PC Performance Boost",
    description: "Kills unnecessary processes, optimizes power plan, and clears all caches.",
    longDescription: "This all-in-one performance boost kills unnecessary background processes, sets the power plan to High Performance, clears all caches (DNS, icon, thumbnail, font, temp files), disables unnecessary visual effects, and optimizes memory management. It is safe and reversible with the included undo file.",
    category: "Performance",
    icon: Zap,
    fixPrompt: "I want to make my PC run as fast as possible. Give me a full performance boost that optimizes everything safely.",
    downloads: 9250,
  },
  {
    slug: "gaming-optimize",
    title: "Optimize PC for Gaming",
    description: "Enables Game Mode, optimizes GPU settings, and reduces gaming latency.",
    longDescription: "This fix enables Windows Game Mode, sets GPU to maximum performance, disables background processes that cause FPS drops, optimizes network settings for low latency, and configures power settings for gaming. It also disables fullscreen optimizations and the Xbox Game Bar overlay.",
    category: "Performance",
    icon: Zap,
    fixPrompt: "I want to optimize my PC for the best gaming performance. Enable Game Mode, max GPU performance, and reduce latency.",
    downloads: 5870,
  },
  {
    slug: "auto-cleanup",
    title: "Automatic Weekly Cleanup",
    description: "Sets up a scheduled weekly cleanup of temp files, cache, and Recycle Bin.",
    longDescription: "This fix creates a scheduled task that runs weekly to clean up temporary files, clear all caches, empty the Recycle Bin, and remove old Windows Update files. It runs silently in the background and keeps your PC running smoothly without manual maintenance.",
    category: "Automation",
    icon: HardDrive,
    fixPrompt: "I want to set up automatic weekly cleanup of temp files, cache, and recycle bin so my PC stays fast.",
    downloads: 2890,
  },
  {
    slug: "ssd-optimize",
    title: "Optimize SSD Performance",
    description: "Enables TRIM, disables defragmentation, and optimizes SSD write caching.",
    longDescription: "This fix enables TRIM for all SSD drives, disables scheduled defragmentation on SSDs, optimizes write caching, and disables unnecessary SSD-unfriendly services. It ensures your SSD runs at maximum speed and lasts longer.",
    category: "Performance",
    icon: HardDrive,
    fixPrompt: "I have an SSD and I want to optimize it for maximum performance and longevity. Enable TRIM and disable defragmentation.",
    downloads: 3420,
  },
  {
    slug: "remove-bloatware",
    title: "Remove Manufacturer Bloatware",
    description: "Unlocks and uninstalls common manufacturer bloatware and pre-installed junk apps.",
    longDescription: "New PCs come loaded with manufacturer bloatware, trial apps, and junk that slows down your system. This fix identifies and removes the most common bloatware including manufacturer utilities, trial antivirus, game bars, and promotional apps. It creates a restore point before removing anything.",
    category: "Setup & Installation",
    icon: Shield,
    fixPrompt: "My new PC came with a lot of bloatware and pre-installed junk apps. Remove all manufacturer bloatware safely.",
    downloads: 6780,
  },
]

export const COMMUNITY_CATEGORIES = [
  "Fix Tools",
  "Performance",
  "Privacy & Security",
  "Customization",
  "Automation",
  "Setup & Installation",
]

export function getCommunityFix(slug: string): CommunityFix | undefined {
  return COMMUNITY_FIXES.find((fix) => fix.slug === slug)
}