export const SAFETY_RULES = [
  "The script MUST begin with a silent system scan relevant to the specific problem BEFORE applying any fix. The scan determines the actual state of the system so the fix is targeted, not generic.",
  "The script MUST display only friendly plain English messages in the console window. Never show raw PowerShell output, error codes, or technical jargon. Use messages like 'Checking your network settings...' or 'Applying fix...'. Format all messages with Write-Host.",
  "The script MUST capture original settings BEFORE changing anything and save them as PowerShell variables. This includes registry values, service states, active power plans, network configurations, and any other system state that will be modified.",
  "The script MUST log every action taken to a log variable throughout execution. Each log entry must include a timestamp, the action performed, and the result. Example: $log += \"[$(Get-Date -Format 'HH:mm:ss')] Reset DNS cache - Success\"",
  "The script MUST copy the full log to clipboard automatically when finished using Set-Clipboard -Value $log. The user must be told in the completion message that the log has been copied to clipboard.",
  "The script MUST generate and save undo data BEFORE making any change. The undo script must be a separate complete BAT file that restores all original settings. Both the fix and undo must be self-contained.",
  "The script MUST include a clear completion message telling the user what was done and that the fix is complete. The message should say something like: 'Fix complete! Your [problem area] has been repaired. A log has been copied to your clipboard.'",
  "The script MUST use only standard Windows system paths. Never assume specific user paths like C:\\Users\\John without first scanning for them using environment variables like $env:USERPROFILE, $env:APPDATA, $env:ProgramFiles, etc.",
  "The script MUST NEVER download any executable file except through the official Windows Package Manager (Winget) or direct microsoft.com URLs. No third-party download links are allowed.",
  "The script MUST NEVER use encoded or obfuscated commands. All code must be plain readable PowerShell that any user can understand by reading it. No Base64, no -EncodedCommand, no hidden commands.",
  "The script MUST NEVER disable Windows Defender or any security software. The script must never add exclusions to antivirus, never turn off real-time protection, and never suggest the user disable security features.",
  "The script MUST NEVER modify the Windows registry without first backing up the affected keys to a .reg file. The backup must be saved in the same directory as the script with a clear name like 'RegistryBackup_[timestamp].reg'.",
  "After applying each change, the script MUST VERIFY the result by re-checking the actual system state — not just assuming the command worked — and log an explicit confirmation line. CRITICAL: Do NOT log \"Success\" or \"Verified\" immediately after running a command. Instead, run a SECOND command to check the result, then log \"Verified: <what was confirmed>\" or \"Could not verify: <what was expected>\". Example BAD (do not do): Set-ItemProperty ...; Write-Log \"Disabled audio enhancements - Success\". Example GOOD (do this): Set-ItemProperty ...; $check = Get-ItemProperty ...; if ($check.Enable -eq 0) { Write-Log \"Verified: audio enhancements disabled\" } else { Write-Log \"Could not verify: audio enhancements still enabled\" }. COM example BAD: $snd.settings.volume = 50; Write-Log \"Verified: volume reset\". COM example GOOD: $snd.settings.volume = 50; $actual = $snd.settings.volume; if ($actual -eq 50) { Write-Log \"Verified: volume set to 50\" } else { Write-Log \"Could not verify: volume is $actual instead of 50\" }. A verification line MUST appear in the log for every change the script makes.",
  "CRITICAL — NEVER use fabricated/non-existent PowerShell cmdlets or WMI classes. These DO NOT EXIST and MUST NOT be used: Set-DefaultAudioDevice, Set-Volume -Level, Set-Volume -Permanent, Get-Process -Name 'System Sounds', Get-AudioDevice, Win32_Volume.SetVolume, MSiTunes_Sound_Device (fabricated WMI class), any AudioDeviceCmdlets module cmdlet, any cmdlet with a parameter named -Permanent, any cmdlet named Set-Default*. If you use any of these, the script will fail entirely. CORRECT alternatives: Get-PnpDevice -Class Sound for audio devices, New-Object -ComObject \"WMPlayer.OCX\"; $_.settings.volume for volume control, reg.exe for registry. For setting default audio device: there is NO cmdlet or WMI class — instead open Sound settings with rundll32.exe shell32.dll,Control_RunDLL mmsys.cpl,,0 and guide the user. If you are unsure a cmdlet or WMI class exists, use reg.exe, netsh, sc.exe, or COM objects instead.",
  "The script MUST NOT access registry keys without first checking they exist using Test-Path. If a registry path does not exist, log it and skip that step — do NOT log a fake success. Example: if (-not (Test-Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Audio')) { Write-Log \"Skipping audio registry tweaks — path not found\" \"Yellow\" } else { ... make changes ...; Write-Log \"Verified: audio registry tweaks applied\" }. Never create registry keys that were not there before unless the user specifically asked for a new setting to be configured.",
  "Each Write-Log message MUST truthfully describe what the following code block actually does. Do NOT write a header like 'Disabling audio enhancements...' unless the code underneath actually modifies enhancement settings. If a block only sets volume, the header must say 'Resetting volume levels...' not 'Disabling audio enhancements...'. The user sees these messages — misleading headers break trust.",
  "SCOPE GUARD — If the user's request is not a legitimate Windows repair, optimization, or configuration task (for example it asks to delete personal files, crack or pirate software, attack or spy on another person, or anything unrelated to fixing a Windows PC), do NOT generate a script. Instead return JSON where problemSummary politely explains you can only help with Windows repair and optimization, and fixScript and undoScript are empty strings.",
] as const

export function formatSafetyRules(): string {
  return SAFETY_RULES.map((rule, i) => `${i + 1}. ${rule}`).join("\n")
}
